custom:
  jwt:
    secretKey: whatKindOfAppleDoYouLike?IsentAMessageAndCheckDescriptionBelowWhatKindOfAppleDoYouLike?IsentAMessageAndCheckDescriptionBelowWhatKindOfAppleDoYouLike?IsentAMessageAndCheckDescriptionBelow
