custom:
  jwt:
    secretKey: whatKindOfAppleDoYouLike?ISentAMessageAndCheckDescriptionBelowWhatKindOfAppleDoYouLike?ISentAMessageAndCheckDescriptionBelowWhatKindOfAppleDoYouLike?ISentAMessageAndCheckDescriptionBelow
